export const environment = {
  appVersion: require('../../package.json').version + '-hmg',
  production: false,
  label:'Homologação - ',
  apiURLLogin:'https://hmg.amhp.com.br/api',
  apiURLAMHPTISS:'https://hmg.amhp.com.br/api',
  apiURLProfissionalSaude:'https://hmg.amhp.com.br/api',
  apiURLConta:'https://censo-api-hmg.amhp.com.br/api/Conta',
  apiURLUpload:'https://censo-api-hmg.amhp.com.br/api/Upload',
  apiURLChecklist: 'https://censo-api-hmg.amhp.com.br/api/Checklist',
  apiURLFiltro: 'https://censo-api-hmg.amhp.com.br/api/Filtro',
  apiURLTabela:'https://censo-api-hmg.amhp.com.br/api/Tabela',
  apiURLUsuario:'https://censo-api-hmg.amhp.com.br/api/Usuario',
  apiURLServicos:'https://censo-api-hmg.amhp.com.br/api/Servico',
  apiURLCobranca:'https://censo-api-hmg.amhp.com.br/api/Cobranca',
  apiURLAtendimentos:'https://censo-api-hmg.amhp.com.br/api/Censo',
  apiURLEstatistica:'https://censo-api-hmg.amhp.com.br/api/Estatistica',
  apiURLAuditoria:'https://censo-api-hmg.amhp.com.br/api/Auditoria',
  apiURLRelatorio:'https://censo-api-hmg.amhp.com.br/api/Relatorio',
  apiURLOperadora:'https://censo-api-hmg.amhp.com.br/api/Operadora',
  apiURLAcomodacao:'https://censo-api-hmg.amhp.com.br/api/Acomodacao',
  apiURLInternacao:'https://censo-api-hmg.amhp.com.br/api/Internacao',
  apiURLLocalConta: 'https://censo-api-hmg.amhp.com.br/api/LocalConta',
  apiURLStatusConta:'https://censo-api-hmg.amhp.com.br/api/StatusConta',
  apiURLContaPendencia:'https://censo-api-hmg.amhp.com.br/api/ContaPendencia',
  apiURLCodigos:'https://censo-api-hmg.amhp.com.br/api/CodigosCentroCirurgico',
  apiURLServicoValorado:'https://censo-api-hmg.amhp.com.br/api/ServicoValorado',
  apiURLCentroCirurgico:'https://censo-api-hmg.amhp.com.br/api/CentroCirurgico',
  apiURLTabelaOperadora:'https://censo-api-hmg.amhp.com.br/api/TabelaOperadora',
  apiURLMotivoPendencia:'https://censo-api-hmg.amhp.com.br/api/MotivoPendencia',
  apiURLServicoCobranca:'https://censo-api-hmg.amhp.com.br/api/ServicoCobranca',
  apiURLLocalAtendimento:'https://censo-api-hmg.amhp.com.br/api/LocalAtendimento',
  apiURLUnidadeOperadora:'https://censo-api-hmg.amhp.com.br/api/UnidadeOperadora',
  apiURLGEDCensoContaArquivo: 'https://amhpged.amhp.com.br/api/CensoContaArquivo',
  apiURLGEDDownloadArquivoGED: 'https://amhpged.amhp.com.br/api/DownloadArquivo',
  apiURLRegistroAtendimentos:'https://censo-api-hmg.amhp.com.br/api/RegistroAtendimento',
  apiURLCobrancaCorpoClinico:'https://censo-api-hmg.amhp.com.br/api/CobrancaCorpoClinico',
  apiURLGEDTipoDocumentoCensoConta: 'https://amhpged.amhp.com.br/api/TipoDocumentoCensoConta',
  apiURLObservacaoInativaServico: 'https://censo-api-hmg.amhp.com.br/api/ObservacaoInativaServico',
};
