export const environment = {
  appVersion: require('../../package.json').version + '-dev',
  production: false,
  label:'Desenvolvimento - ',
  apiURLLogin:'https://hmg.amhp.com.br/api',
  apiURLAMHPTISS:'http://localhost:33000/api',
  apiURLConta:'https://localhost:7009/api/Conta',
  apiURLTabela:'https://localhost:7009/api/Tabela',
  apiURLUpload:'https://localhost:7009/api/Upload',
  apiURLFiltro: 'https://localhost:7009/api/Filtro',
  apiURLUsuario:'https://localhost:7009/api/Usuario',
  apiURLServicos:'https://localhost:7009/api/Servico',
  apiURLCobranca:'https://localhost:7009/api/Cobranca',
  apiURLAtendimentos:'https://localhost:7009/api/Censo',
  apiURLProfissionalSaude:'https://hmg.amhp.com.br/api',
  apiURLAuditoria:'https://localhost:7009/api/Auditoria',
  apiURLRelatorio:'https://localhost:7009/api/Relatorio',
  apiURLOperadora:'https://localhost:7009/api/Operadora',
  apiURLChecklist: 'https://localhost:7009/api/Checklist',
  apiURLAcomodacao:'https://localhost:7009/api/Acomodacao',
  apiURLInternacao:'https://localhost:7009/api/Internacao',
  apiURLLocalConta: 'https://localhost:7009/api/LocalConta',
  apiURLStatusConta:'https://localhost:7009/api/StatusConta',
  apiURLEstatistica:'https://localhost:7009/api/Estatistica',
  apiURLContaPendencia:'https://localhost:7009/api/ContaPendencia',
  apiURLCodigos:'https://localhost:7009/api/CodigosCentroCirurgico',
  apiURLServicoValorado:'https://localhost:7009/api/ServicoValorado',
  apiURLTabelaOperadora:'https://localhost:7009/api/TabelaOperadora',
  apiURLMotivoPendencia:'https://localhost:7009/api/MotivoPendencia',
  apiURLCentroCirurgico:'https://localhost:7009/api/CentroCirurgico',
  apiURLServicoCobranca:'https://localhost:7009/api/ServicoCobranca',
  apiURLLocalAtendimento:'https://localhost:7009/api/LocalAtendimento',
  apiURLUnidadeOperadora:'https://localhost:7009/api/UnidadeOperadora',
  apiURLGEDDownloadArquivoGED: 'https://localhost:7222/api/DownloadArquivo',
  apiURLGEDCensoContaArquivo: 'https://localhost:7222/api/CensoContaArquivo',
  apiURLRegistroAtendimentos:'https://localhost:7009/api/RegistroAtendimento',
  apiURLCobrancaCorpoClinico:'https://localhost:7009/api/CobrancaCorpoClinico',
  apiURLObservacaoInativaServico: 'https://localhost:7009/api/ObservacaoInativaServico',
  apiURLGEDTipoDocumentoCensoConta: 'https://localhost:7222/api/TipoDocumentoCensoConta',
};
