export const environment = {
  appVersion: require('../../package.json').version,
  production: true,
  label:'',
  apiURLLogin: 'https://amhptiss.amhp.com.br/api',
  apiURLAMHPTISS: 'https://amhptiss.amhp.com.br/api',
  apiURLConta:'https://censo-api.amhp.com.br/api/Conta',
  apiURLUpload:'https://censo-api.amhp.com.br/api/Upload',
  apiURLTabela:'https://censo-api.amhp.com.br/api/Tabela',
  apiURLUsuario:'https://censo-api.amhp.com.br/api/Usuario',
  apiURLProfissionalSaude:'https://amhptiss.amhp.com.br/api',
  apiURLFiltro: 'https://censo-api.amhp.com.br/api/Filtro',
  apiURLServicos:'https://censo-api.amhp.com.br/api/Servico',
  apiURLCobranca:'https://censo-api.amhp.com.br/api/Cobranca',
  apiURLAtendimentos:'https://censo-api.amhp.com.br/api/Censo',
  apiURLOperadora:'https://censo-api.amhp.com.br/api/Operadora',
  apiURLAuditoria:'https://censo-api.amhp.com.br/api/Auditoria',
  apiURLChecklist: 'https://censo-api.amhp.com.br/api/Checklist',
  apiURLRelatorio:'https://censo-api.amhp.com.br/api/Relatorio',
  apiURLAcomodacao:'https://censo-api.amhp.com.br/api/Acomodacao',
  apiURLInternacao:'https://censo-api.amhp.com.br/api/Internacao',
  apiURLLocalConta: 'https://censo-api.amhp.com.br/api/LocalConta',
  apiURLEstatistica:'https://censo-api.amhp.com.br/api/Estatistica',
  apiURLStatusConta:'https://censo-api.amhp.com.br/api/StatusConta',
  apiURLContaPendencia:'https://censo-api.amhp.com.br/api/ContaPendencia',
  apiURLCodigos:'https://censo-api.amhp.com.br/api/CodigosCentroCirurgico',
  apiURLTabelaOperadora:'https://censo-api.amhp.com.br/api/TabelaOperadora',
  apiURLCentroCirurgico:'https://censo-api.amhp.com.br/api/CentroCirurgico',
  apiURLMotivoPendencia:'https://censo-api.amhp.com.br/api/MotivoPendencia',
  apiURLServicoCobranca:'https://censo-api.amhp.com.br/api/ServicoCobranca',
  apiURLUnidadeOperadora:'https://censo-api.amhp.com.br/api/UnidadeOperadora',
  apiURLLocalAtendimento:'https://censo-api.amhp.com.br/api/LocalAtendimento',
  apiURLServicoValorado:'https://censo-api.amhp.com.br/api/ServicoValorado',
  apiURLGEDDownloadArquivoGED: 'https://amhpged.amhp.com.br/api/DownloadArquivo',
  apiURLGEDCensoContaArquivo: 'https://amhpged.amhp.com.br/api/CensoContaArquivo',
  apiURLRegistroAtendimentos:'https://censo-api.amhp.com.br/api/RegistroAtendimento',
  apiURLCobrancaCorpoClinico:'https://censo-api.amhp.com.br/api/CobrancaCorpoClinico',
  apiURLGEDTipoDocumentoCensoConta: 'https://amhpged.amhp.com.br/api/TipoDocumentoCensoConta',
  apiURLObservacaoInativaServico: 'https://censo-api.amhp.com.br/api/ObservacaoInativaServico',
};
